site_name: 'Acren Wiki'
site_url: https://wiki.acren.org
site_author: 'Acren Team'
site_description: 'Learn about Acren'
repo_name: '/AcrenEnv-wiki'
repo_url: https://github.com/AcrenEnv/wiki
edit_uri: edit/master/wiki/
docs_dir: wiki


theme:
  name: null
  custom_dir: material
  language: en
  palette:
    primary: Light Green
    accent: Light Green
  font:
    text: Roboto
    code: Roboto Mono
  logo:
    icon: "\uE80C"
  feature:
    tabs: false

nav:
    -  Welcome: 'index.md'
    -  Acren Overview: 
        - About Acren: 'acrenOverview/index.md'
        - Vision: 'acrenOverview/vision.md'
        - Mission: 'acrenOverview/mission.md'
        - Roadmap: 'acrenOverview/roadmap.md'
    -  Technical Overview: 
        - Structure: 'technicalOverview/index.md'
        - Developer Guide: 'technicalOverview/index.md'
    -  Project management: 
        - Overview: 'projectManagement/index.md'
        - Goal of System: 'technicalOverview/index.md'
        - Actors: 'technicalOverview/index.md'
        - User-Stories: 'technicalOverview/index.md'
        - Smart Contracts: 'technicalOverview/index.md'
        - Frontend: 'technicalOverview/index.md'
        - Tests & Security: 'technicalOverview/index.md'
    -  More: 
        - FAQ: 'more/index.md'